### PR TITLE
Align uuid/ack handling with core scheduler driver, and MORE

### LINKED ISSUE #156: status-update-ack's with empty slave-id crash the scheduler driver
... and this is breaking certain task-launch failure scenarios. for context, see https://github.com/mesosphere/kubernetes-mesos/issues/426#issuecomment-128596383

### PR DESCRIPTION
**Pull request by jdef**
motivation:
- fixes #156 

other things that happened on the way:
- i want all the unit tests passing (kill the data races!)
- i want the synchronization code in the scheduler and executor to be (more) reasonable (helps with the above)
- updated godeps to latest samuel/go-zookeeper
- `make check` should ignore files in `Godeps/`
- use travis' container-based infra
- hijack the net/http server connections to implement decoding that's compat with mesos libprocess
- added support for ExitedExecutor message (--> Scheduler.ExecutorLost)

todo:
- [x] unit test for `updateRequiresAck` logic
- [x] fix remaining zk test flakes
- [x] test example scheduler/executor against running mesos cluster
- [x] the HTTP lib workarounds currently require go1.5 -- this probably won't work for all frameworks that require 1.3/1.4 API compat.

xref https://issues.apache.org/jira/browse/MESOS-2865

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -1,36 +1,40 @@
...
 formatted:
-	! gofmt -s -d . 2>&1 | read diff
+	! gofmt -s -l . | grep -v -e ^Godeps/
 
 vet:
 	go vet ./...
 
 test:
-	go test -timeout 60s -race ./...
+	go test -timeout 300s -race ./...
```
Comment (jdef) [inline Makefile]: use `${RACE}` flag

File: detector/zoo/detect.go [hunk 2]
```diff
@@ -187,57 +191,97 @@ func (md *MasterDetector) notifyAllMasters(path string, list []string, obs detec
 // once, and each time the spec'd listener will be added to the list of those receiving notifications.
 func (md *MasterDetector) Detect(f detector.MasterChanged) (err error) {
 	// kickstart zk client connectivity
-	md.bootstrap.Do(func() { go md.client.connect() })
+	if err := func() (e error) {
```
Comment (jdef) [inline detector/zoo/detect.go]: factor this out into a separate func `invokeBootstrap()` or something

File: detector/zoo/detect.go [hunk 3]
```diff
@@ -187,57 +191,97 @@ func (md *MasterDetector) notifyAllMasters(path string, list []string, obs detec
...
+				// doing this is that a listener might get two callbacks back-to-back ("new leader",
+				// followed by "no leader").
 				select {
-				case <-watchEnded:
+				case children := <-childrenCh:
+					md.childrenChanged(path, children, f)
+				default:
+				}
+				if ok {
+					log.V(1).Infoln("child watch ended with error, signaling master lost; error was:", err.Error())
```
Comment (jdef) [inline detector/zoo/detect.go]: remove the word signalling, because we don't always do it (for example, if the leader is already == "")

File: examples/example_scheduler.go [hunk 4]
```diff
@@ -215,7 +231,7 @@ func prepareExecutorInfo() *mesos.ExecutorInfo {
 	uri, executorCmd := serveExecutorArtifact(*executorPath)
 	executorUris = append(executorUris, &mesos.CommandInfo_URI{Value: uri, Executable: proto.Bool(true)})
 
-	executorCommand := fmt.Sprintf("./%s", executorCmd)
+	executorCommand := fmt.Sprintf("./%s -logtostderr=true -v=3", executorCmd)
```
Comment (jdef) [inline examples/example_scheduler.go]: remove `-v=3` or else pass through the value of `-v` from the scheduler

Comment (jdef) [inline examples/example_scheduler.go]: might also be nice to pass through the value of `GLOG_v` envvar

File: executor/executor.go [hunk 5]
```diff
@@ -88,14 +88,22 @@ func NewMesosExecutorDriver(config DriverConfig) (*MesosExecutorDriver, error) {
...
+		updates: make(map[string]*mesosproto.StatusUpdate),
+		tasks:   make(map[string]*mesosproto.TaskInfo),
+		workDir: ".",
+		started: make(chan struct{}),
+	}
+	driver.cond = sync.NewCond(&driver.lock)
+	// decouple serialized executor callback execution from goroutines of this driver
+	var execLock sync.Mutex
+	driver.withExecutor = func(f func(e Executor)) {
+		go func() {
```
Comment (jdef) [inline executor/executor.go]: invoking callbacks this way (here, and in the scheduler) is essentially enqueuing operations into a limitless, unordered queue. may break guarantees of libprocess communication. need to validate w/ core team.

File: executor/executor.go [hunk 6]
```diff
@@ -427,105 +433,142 @@ func (driver *MesosExecutorDriver) Start() (mesosproto.Status, error) {
...
+	defer driver.lock.Unlock()
+	return driver.run()
+}
+
+func (driver *MesosExecutorDriver) run() (mesosproto.Status, error) {
+	stat, err := driver.start()
 
 	if err != nil {
-		return driver.Stop()
+		return driver.stop()
```
Comment (jdef) [inline executor/executor.go]: this is pretty aggressive. consider that the driver has already been started and then the caller invokes run(). would it not be better to return `(DRIVER_RUNNING, ErrAlreadyRunning)` instead of stopping the driver?

File: messenger/decoder.go [hunk 7]
```diff
@@ -0,0 +1,465 @@
...
+	DefaultReadTimeout = 5 * time.Second
+)
+
+type decoderID int32
+
+func (did decoderID) String() string {
+	return "[" + strconv.Itoa(int(did)) + "]"
+}
+
+func (did *decoderID) Next() decoderID {
```
Comment (jdef) [inline messenger/decoder.go]: make Next() non-public

File: messenger/decoder.go [hunk 8]
```diff
@@ -0,0 +1,465 @@
...
+func (l *limitReadCloser) Close() error {
+	// discard remaining
+	_, err := l.r.Discard(int(l.LimitedReader.N)) // TODO(jdef) possible overflow
+	return err
+}
+
+// bootstrapState expects to be called when the standard net/http lib has already
+// read the initial request query line + headers from a connection. the request
+// is ready to be hijacked at this point.
+func bootstrapState(d *httpDecoder) httpState {
```
Comment (jdef) [inline messenger/decoder.go]: refactor this so that it's invoked DecodeHTTP and not actually a state. Then get rid of httpDecoder.res

File: messenger/decoder.go [hunk 9]
```diff
@@ -0,0 +1,465 @@
...
+	}
+	r := d.req
+	r.Method = ss[0]
+	r.RequestURI = ss[1]
+	r.URL, err = url.ParseRequestURI(ss[1])
+	if err != nil {
+		d.errCh <- err
+		return terminateState
+	}
+	major, minor, ok := http.ParseHTTPVersion(ss[2])
```
Comment (jdef) [inline messenger/decoder.go]: validate protocol versions?

File: messenger/decoder.go [hunk 10]
```diff
@@ -0,0 +1,465 @@
...
+
+func readHeaderState(d *httpDecoder) httpState {
+	log.V(2).Infoln(d.idtag + "read-header-state")
+	if !d.setReadTimeout() {
+		return terminateState
+	}
+	r := d.req
+	tr := textproto.NewReader(d.rw.Reader)
+	h, err := tr.ReadMIMEHeader()
+	for k, v := range h {
```
Comment (jdef) [inline messenger/decoder.go]: add a comment here: merge any headers that were read (before a possible error)

File: messenger/http_transporter.go [hunk 11]
```diff
@@ -261,39 +395,43 @@ func (t *HTTPTransporter) listen() error {
...
 	ch := make(chan error, 1)
 	if err := t.listen(); err != nil {
 		ch <- err
 	} else {
 		// TODO(yifan): Set read/write deadline.
-		log.Infof("http transport listening on %v", t.listener.Addr())
 		go func() {
-			err := http.Serve(t.listener, t.mux)
+			s := &http.Server{
+				// ReadTimeout: 5 * time.Second,
```
Comment (jdef) [inline messenger/http_transporter.go]: probably want ReadTimeout to align with the decoder DefaultReadTimeout: should only impact reading the request-line and headers of the initial request.

File: messenger/http_transporter.go [hunk 12]
```diff
@@ -326,6 +462,47 @@ func (t *HTTPTransporter) UPID() *upid.UPID {
...
+			continue
+		}
+		if err, ok := <-decoder.Err(); ok {
+			log.Errorf("failed to decode HTTP message: %v", err)
+			return
+		}
+	}
+}
+
+/*
```
Comment (jdef) [inline messenger/http_transporter.go]: remove this code for now until mesos implements proper HTTP pipeline semantics.

File: messenger/messenger.go [hunk 13]
```diff
@@ -266,12 +274,15 @@ func (m *MesosMessenger) Start() error {
 
 // Stop stops the messenger and clean up all the goroutines.
 func (m *MesosMessenger) Stop() error {
+	defer m.stopOnce.Do(func() { close(m.stop) })
```
Comment (jdef) [inline messenger/messenger.go]: instead of stopOnce use an atomic/int32 latch to guard execution of this entire func

File: scheduler/scheduler.go [hunk 14]
```diff
@@ -177,15 +178,30 @@ func NewMesosSchedulerDriver(config DriverConfig) (initializedDriver *MesosSched
...
+	driver.eventCond = sync.NewCond(&driver.eventLock)
+
+	// mechanism that allows us to asynchronously invoke scheduler callbacks, but in a manner
+	// such that the callback invocations are serialized. useful because this will decouple the
+	// goroutine executing a messenger callback from the goroutine executing a scheduler callback,
+	// while preserving the serialization semantics for each type of callback handling.
+	// note, however, that the order of the messages processed by the messenged callback handlers,
+	// and the order of the callbacks invoked upon the scheduler may be different.
+	var schedLock sync.Mutex
+	driver.withScheduler = func(f func(s Scheduler)) {
```
Comment (jdef) [inline scheduler/scheduler.go]: see comments in the executor about concerns re: ordering guarantees

File: executor/executor.go (hunk 5 above)
Comment (jdef) [inline executor/executor.go]: status updates are expected to be delivered in-order. are they timestamped? what's the delivery window look like? how strict is this?

Comment (jdef) [inline executor/executor.go]: status updates are ack'd -- the scheduler won't get another status update for the same task until a prior update message has been ack'd. this means that we should do our best to preserve the order of execution w/ respect to (at least) status update messages.

**Comment by jdef** [comment]
flaky unit test:
```
--- FAIL: TestAuthticatee_validLogin-2 (1.00 seconds)
	Error Trace:	authenticatee_test.go:102
	Error:		Expected nil, but got: &errors.errorString{s:"Unexpected authentication 'mechanisms' received"}
		
	<autogenerated>:29: ✅	Install()
	<autogenerated>:29: ✅	UPID()
	<autogenerated>:29: ✅	Start()
	<autogenerated>:29: ✅	Stop()
	<autogenerated>:29: ✅	Send(string,*upid.UPID,*mesosproto.AuthenticateMessage)
	<autogenerated>:29: ❌	Send(string,*upid.UPID,*mesosproto.AuthenticationStartMessage)
	<autogenerated>:29: ❌	Send(string,*upid.UPID,*mesosproto.AuthenticationStepMessage)
	<autogenerated>:31: FAIL: 5 out of 7 expectation(s) were met.
			The code you are testing needs to make 2 more call(s).
			at: [authenticatee_test.go:105]
```

**Comment by spacejam** [comment]
I've performed this manual testing on this branch:
situations passed: initial zk detection, creating initial tasks for my test scheduler, <restart test scheduler> zk detection, reconciling tasks, <kill several tasks> receiving TASK_LOST messages and launching new ones, <restart mesos master> redetect mesos master and reconcile successfully

**Comment by jdef** [comment]
Thanks for beating on this @spacejam

**Comment by tsenart** [comment]
:clap: :clap: :clap:

**Comment by tsenart** [comment]
LGTM

**Comment by jdef** [comment]
@tsenart I'm going to push one more change that I forgot to mention earlier this morning, has to do with the order of processing status updates

**Comment by tsenart** [comment]
OK

**Comment by jdef** [comment]
I've made the changes locally, waiting for GH ops to re-push this branch

**Comment by tsenart** [comment]
@jdef: You should be able to push again. Please merge this into master once you do.
